name: Build NetherSX2 and Patch APKs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xdelta3 zipalign

      - name: Build NetherSX2 and Patch APKs
        run: python3 scripts/build.py

      - name: Upload Adreno APK
        uses: actions/upload-artifact@v4
        with:
          name: xyz.aethersx2.android_adreno.apk
          path: xyz.aethersx2.android_adreno.apk
          if-no-files-found: error

      - name: Upload Mali APK
        uses: actions/upload-artifact@v4
        with:
          name: xyz.aethersx2.android_mali.apk
          path: xyz.aethersx2.android_mali.apk
          if-no-files-found: error

      - name: Upload xdelta
        uses: actions/upload-artifact@v4
        with:
          name: xyz.aethersx2.android_.xdelta
          path: xyz.aethersx2.android_.xdelta
          if-no-files-found: error
